export const config = {
  spreadsheet: {
    baseURL: import.meta.env.VITE_SPREADSHEET_URL || "https://docs.google.com/spreadsheets/d/",
  },
  cookie: {
    cookieNameAuth: "auth.user",
    cookieNameSheetFileData: "sheet.file.data",
    cookieNameFigmaJwt: "figmaJwt",
  },
  api: {
    baseURL: import.meta.env.VITE_API_URL,
    timeout: 10_000,
    endpoints: {
      auth: "/auth",
      refreshAccessToken: "/api/auth/refresh",
      sheetCreate: "/api/sheets/create",
      sheetGetByURL: "/api/sheets/get-by-url",
      checkSheetValid: "/api/sheets/check-sheet-valid",
      addColor: "/api/database-sheets/add-color",
      addMultipleColors: "/api/database-sheets/add-multiple-colors",
      upsertColors: "/api/database-sheets/upsert-colors",
      updateRow: "/api/database-sheets/update-row",
      deleteRow: "/api/database-sheets/delete-row",
      checkAddOrUpdate: "/api/sheets/check-add-or-update",
      addColumn: "/api/sheets/add-column",
      removeColumn: "/api/sheets/remove-column",
      getAdditionalColumns: "/api/sheets/get-additional-columns",
      figmaAuth: "/figma/auth",
      figmaBindAccount: "/figma/bind",
      figmaGetAccounts: "/figma/accounts",
      figmaGetTeams: "/figma/teams",
      figmaAddTeam: "/figma/add-team",
      figmaGetProjects: "/figma/projects",
      figmaGetFiles: "/figma/files",
      figmaAddColors: "/figma/add-colors",
      figmaDeleteAccount: "/figma/delete-account",
      figmaDeleteTeam: "/figma/delete-team",
      paletteCreate: "/api/palettes/create",
      paletteGet: "/api/palettes",
      paletteUpdate: "/api/palettes",
      paletteDelete: "/api/palettes",
      getColorsAndPalettes: "/api/database-sheets/colors-and-palettes",
      getFolders: "/api/folders",
      updateColor: "/api/database-sheets/update-color-by-id",
      copyColorToFolder: "/api/folders",
      moveColorsToFolder: "/api/folders",
    },
  },
  toast: {
    timeout: 2_000,
  },
  limitations: {
    maxFiles: 2,
    maxAdditionalColumns: 1,
  },
}
